name: Rust

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./navier_stokes_rust

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose